### ISSUE TITLE
Does not seem to detect difference when a key is in 'actual' JSON that is not in the 'expected' JSON

### ISSUE THREAD

**Issue by jolsen71** [rugleb/JsonCompare#11]
It seems like the module is not checking for keys that exist in the "actual" structure that are not in the "expected" structure.

Example code:
```python
expected = {'a': 1, 'b': 'tom'}
actual = {'a': 1, 'b': 'tom', 'c': 'surprise'}
diff = Compare().check(expected, actual)
```
This reports no differences, even though they are clearly not identical. I would like this condition to be included in the diff report, perhaps as an `UnexpectedKey` exception with a message of `Unexpected key. Received: <{r}>`

If this is already supported, please let me know how to enable it. 

Thanks

**Comment by rugleb** [comment]
Hi! In fact, this was intended when I wrote this package for internal needs. Therefore, this can be perceived as a feature, not a bug 😝

In general, I agree that this behavior is unexpected and it is worth fixing.

Unfortunately, I don't have time to fix this error right now. So send a PR if you have a time to fix it.
