### ISSUE TITLE
exclude entries within a list of objects of a more complex JSON structure

### ISSUE THREAD

**Issue by NikiDev1** [rugleb/JsonCompare#24]
Hi Karpushkin.

I worked with your great library for comparing JSON files. Your Readme and your samples are very helpful. 
So I could compare simple JSON files easily.

But I'm stuck in a rule for nodes within a list of objects. Would you tell me please, how I have to use the rules in the right manner?

My structure is like this:
{
  "A" : {
    "B" : [ {
      "C" : {
        "D" : "ddd",
        "E" : [ {
          "F" : {
            "G" : "ggg",
            "H" : "hhh"
          }
        } ],
        "I" : "11",
        "J" : null
      }
    } ]
  }
}

What rules I have to use to ignore "G" and "J"?

Thank you in advance, Niko.

**Comment by NikiDev1** [comment]
Hi Karpushkin
Are there any news regarding this issue?
Best, Niko

**Comment by rugleb** [comment]
Hi! Right now, the library does not provide the ability to configure exclusion rules for objects of lists and lists.

**Comment by NikiDev1** [comment]
Hi again, do you plan to extend the lib in the future?

**Comment by rugleb** [comment]
There are no such plans yet
