### ISSUE TITLE
Reverse Comparison not Working

### ISSUE THREAD

**Issue by GRK1997** [rugleb/JsonCompare#28]
if difference exist in -
`Compare().check(first, second)`
Then it should also work for -
`Compare().check(second, first)`

**Comment by rugleb** [comment]
When I was solving a problem on my project, I laid the idea that "expected" may have more data than "actual".

**Comment by GRK1997** [comment]
Okay got it

**Comment by cmortier13** [comment]
Hi, Can you tag a new version?
This has been fixed in Master but not in tags
