### ISSUE TITLE
[Feature Request] Value comparison based on regex

### ISSUE THREAD

**Issue by doradlavamsi** [rugleb/JsonCompare#32]
Let's say we have dictionary actual and expected

expected = {
"namespace": "NamespaceA",
"kind": "Pod" 
}
actual = {
"namespace": "NamespaceA-832y2"
"kind": "pod"
}

In such scenario, I couldn't find utility to do the necessary  comparison using regex. I found a rule "*" this matches any.

**Comment by rugleb** [comment]
Nice idea. Can u implement it?

**Comment by doradlavamsi** [comment]
Will give it a try!

**Comment by MiyamotoAkira** [comment]
As I am interested on having this functionality, I will try to get an implementation this week.

**Comment by rugleb** [comment]
closed in #36
