### ISSUE TITLE
Question about Ignore Rules

### ISSUE THREAD

**Issue by godsmith99x** [rugleb/JsonCompare#45]
Hi,

I really appreciate you creating jsoncompare, and I think it's going to be a great tool for testing my api. However, I am struggling using the ignore rules for a objects nested in a list. I've attached the expected.json, actual.json, ignore rules, and diff.json. If you can give many any help, I would truly appreciate it.

The gist of the problem is that, for each plotRow in my example, there well be unique kmzUrl and geoJsonUrl; so I don't want to compare those values. Though, it would be a bonus if I could still verify if there is some value or a null.

Thanks,
Joel

[actual.json](https://github.com/rugleb/JsonCompare/files/14405811/actual.json)
[diff.json](https://github.com/rugleb/JsonCompare/files/14405812/diff.json)
[expected.json](https://github.com/rugleb/JsonCompare/files/14405813/expected.json)
[ignore_rules.txt](https://github.com/rugleb/JsonCompare/files/14405831/ignore_rules.txt)

**Comment by rugleb** [comment]
Hi! The best solution would be to do preprocessing and convert the list into a dictionary, and then perform a comparison without ignoring rules.

**Comment by godsmith99x** [comment]
> Hi! The best solution would be to do preprocessing and convert the list into a dictionary, and then perform a comparison without ignoring rules.

Thanks!
