### ISSUE TITLE
提示缺少 data/config.json

### ISSUE THREAD

**Issue by lsp84ch83** [rugleb/JsonCompare#8]
pip 安装成功
调用时，提示我缺少 data/config.json，源码追踪后发现，源码里将data/config.json加入到了忽略列表，是否考虑移除忽略，或者在说明文档里说明下，安装后需要自己配置一下

**Comment by jacksgt** [comment]
I am not exactly sure what this fine man is trying to tell us, but I might have the same error.
I installed jsoncomparison via pip in a clean venv:
```
pip install -U pip jsoncomparison
Collecting jsoncomparison
  Using cached jsoncomparison-1.0.0.tar.gz (6.3 kB)
Installing collected packages: jsoncomparison
    Running setup.py install for jsoncomparison ... done
Successfully installed jsoncomparison-1.0.0
```

I used the following minimal example
```
from jsoncomparison import Compare

diff = Compare().check({'foo': 'bar'}, {'hello':'world'})
print(diff)
```
and got the error:
```
python3 mwe.py 
Traceback (most recent call last):
  File "mwe.py", line 5, in <module>
    diff = Compare().check({'foo': 'bar'}, {'hello':'world'})
  File "/home/jack/git/misc/iam/venv/lib/python3.7/site-packages/jsoncomparison/compare.py", line 19, in __init__
    self.set_config(config)
  File "/home/jack/git/misc/iam/venv/lib/python3.7/site-packages/jsoncomparison/compare.py", line 24, in set_config
    config = self.get_default_config()
  File "/home/jack/git/misc/iam/venv/lib/python3.7/site-packages/jsoncomparison/compare.py", line 30, in get_default_config
    with open(path, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jack/git/misc/iam/venv/lib/python3.7/site-packages/jsoncomparison/data/config.json'
```
It seems like the config file is not shipped by default / via pip, it's missing from the tarball:
https://files.pythonhosted.org/packages/f4/12/3bb149fd8149ff10364fe0b8cbe4b483f8d8d877e057682acac04e079785/jsoncomparison-1.0.0.tar.gz

**Comment by DannyBunny** [comment]
> I am not exactly sure what this fine man is trying to tell us, but I might have the same error.
> I installed jsoncomparison via pip in a clean venv:
> 
> ```
> pip install -U pip jsoncomparison
> Collecting jsoncomparison
>   Using cached jsoncomparison-1.0.0.tar.gz (6.3 kB)
> Installing collected packages: jsoncomparison
>     Running setup.py install for jsoncomparison ... done
> Successfully installed jsoncomparison-1.0.0
> ```
> 
> I used the following minimal example
> 
> ```
> from jsoncomparison import Compare
> 
> diff = Compare().check({'foo': 'bar'}, {'hello':'world'})
> print(diff)
> ```
> 
> and got the error:
> 
> ```
> python3 mwe.py 
> Traceback (most recent call last):
>   File "mwe.py", line 5, in <module>
>     diff = Compare().check({'foo': 'bar'}, {'hello':'world'})
>   File "/home/jack/git/misc/iam/venv/lib/python3.7/site-packages/jsoncomparison/compare.py", line 19, in __init__
>     self.set_config(config)
>   File "/home/jack/git/misc/iam/venv/lib/python3.7/site-packages/jsoncomparison/compare.py", line 24, in set_config
>     config = self.get_default_config()
>   File "/home/jack/git/misc/iam/venv/lib/python3.7/site-packages/jsoncomparison/compare.py", line 30, in get_default_config
>     with open(path, 'r') as fp:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/jack/git/misc/iam/venv/lib/python3.7/site-packages/jsoncomparison/data/config.json'
> ```
> 
> It seems like the config file is not shipped by default / via pip, it's missing from the tarball:
> https://files.pythonhosted.org/packages/f4/12/3bb149fd8149ff10364fe0b8cbe4b483f8d8d877e057682acac04e079785/jsoncomparison-1.0.0.tar.gz

same here

**Comment by lsp84ch83** [comment]
> > 我不确定这个好人要告诉我们什么，但我可能有同样的错误。
> > 我通过pip在干净的venv中安装了jsoncomparison：
> > ```
> > pip install -U pip jsoncomparison
> > Collecting jsoncomparison
> >   Using cached jsoncomparison-1.0.0.tar.gz (6.3 kB)
> > Installing collected packages: jsoncomparison
> >     Running setup.py install for jsoncomparison ... done
> > Successfully installed jsoncomparison-1.0.0
> > ```
> > 
> > 
> > 我使用了以下最小示例
> > ```
> > from jsoncomparison import Compare
> > 
> > diff = Compare().check({'foo': 'bar'}, {'hello':'world'})
> > print(diff)
> > ```
> > 
> > 
> > 并得到错误：
> > ```
> > python3 mwe.py 
> > Traceback (most recent call last):
> >   File "mwe.py", line 5, in <module>
> >     diff = Compare().check({'foo': 'bar'}, {'hello':'world'})
> >   File "/home/jack/git/misc/iam/venv/lib/python3.7/site-packages/jsoncomparison/compare.py", line 19, in __init__
> >     self.set_config(config)
> >   File "/home/jack/git/misc/iam/venv/lib/python3.7/site-packages/jsoncomparison/compare.py", line 24, in set_config
> >     config = self.get_default_config()
> >   File "/home/jack/git/misc/iam/venv/lib/python3.7/site-packages/jsoncomparison/compare.py", line 30, in get_default_config
> >     with open(path, 'r') as fp:
> > FileNotFoundError: [Errno 2] No such file or directory: '/home/jack/git/misc/iam/venv/lib/python3.7/site-packages/jsoncomparison/data/config.json'
> > ```
> > 
> > 
> > 似乎默认情况下未通过ip或通过pip发行配置文件，但压缩包中缺少该文件：[https](https://files.pythonhosted.org/packages/f4/12/3bb149fd8149ff10364fe0b8cbe4b483f8d8d877e057682acac04e079785/jsoncomparison-1.0.0.tar.gz) : 
> > [//files.pythonhosted.org/packages/f4/12/3bb149fd8149ff10364fe0b8cbe4b483f8d8d877e057682acac04e079785/jsoncomparison-1.0.0.tar.gz](https://files.pythonhosted.org/packages/f4/12/3bb149fd8149ff10364fe0b8cbe4b483f8d8d877e057682acac04e079785/jsoncomparison-1.0.0.tar.gz)
> 
> 同样在这里

Need to manually set "data / config.json"

**Comment by DannyBunny** [comment]
> > > 我不确定这个好人要告诉我们什么，但我可能有同样的错误。
> > > 我通过pip在干净的venv中安装了jsoncomparison：
> > > ```
> > > pip install -U pip jsoncomparison
> > > Collecting jsoncomparison
> > >   Using cached jsoncomparison-1.0.0.tar.gz (6.3 kB)
> > > Installing collected packages: jsoncomparison
> > >     Running setup.py install for jsoncomparison ... done
> > > Successfully installed jsoncomparison-1.0.0
> > > ```
> > > 
> > > 
> > > 我使用了以下最小示例
> > > ```
> > > from jsoncomparison import Compare
> > > 
> > > diff = Compare().check({'foo': 'bar'}, {'hello':'world'})
> > > print(diff)
> > > ```
> > > 
> > > 
> > > 并得到错误：
> > > ```
> > > python3 mwe.py 
> > > Traceback (most recent call last):
> > >   File "mwe.py", line 5, in <module>
> > >     diff = Compare().check({'foo': 'bar'}, {'hello':'world'})
> > >   File "/home/jack/git/misc/iam/venv/lib/python3.7/site-packages/jsoncomparison/compare.py", line 19, in __init__
> > >     self.set_config(config)
> > >   File "/home/jack/git/misc/iam/venv/lib/python3.7/site-packages/jsoncomparison/compare.py", line 24, in set_config
> > >     config = self.get_default_config()
> > >   File "/home/jack/git/misc/iam/venv/lib/python3.7/site-packages/jsoncomparison/compare.py", line 30, in get_default_config
> > >     with open(path, 'r') as fp:
> > > FileNotFoundError: [Errno 2] No such file or directory: '/home/jack/git/misc/iam/venv/lib/python3.7/site-packages/jsoncomparison/data/config.json'
> > > ```
> > > 
> > > 
> > > 似乎默认情况下未通过ip或通过pip发行配置文件，但压缩包中缺少该文件：[https](https://files.pythonhosted.org/packages/f4/12/3bb149fd8149ff10364fe0b8cbe4b483f8d8d877e057682acac04e079785/jsoncomparison-1.0.0.tar.gz) :
> > > [//files.pythonhosted.org/packages/f4/12/3bb149fd8149ff10364fe0b8cbe4b483f8d8d877e057682acac04e079785/jsoncomparison-1.0.0.tar.gz](https://files.pythonhosted.org/packages/f4/12/3bb149fd8149ff10364fe0b8cbe4b483f8d8d877e057682acac04e079785/jsoncomparison-1.0.0.tar.gz)
> > 
> > 
> > 同样在这里
> 
> Need to manually set "data / config.json"

Thank you

**Comment by rugleb** [comment]
Hello, everyone! I will correct this error in a few days.

**Comment by jacksgt** [comment]
In general, I don't think it is very idiomatic to handle the configuration of a library with JSON files.

I will submit a PR to make this configurable through the class initialization.
